
export const WILAYA_OPTIONS = [
  { value: "1", label: "1 - Adrar" },
  { value: "2", label: "2 - Chlef" },
  { value: "3", label: "3 - Laghouat" },
  { value: "4", label: "4 - Oum El Bouaghi" },
  { value: "5", label: "5 - Batna" },
  { value: "6", label: "6 - Béjaïa" },
  { value: "7", label: "7 - Biskra" },
  { value: "8", label: "8 - Béchar" },
  { value: "9", label: "9 - Blida" },
  { value: "10", label: "10 - Bouira" },
  { value: "11", label: "11 - Tamanrasset" },
  { value: "12", label: "12 - Tébessa" },
  { value: "13", label: "13 - Tlemcen" },
  { value: "14", label: "14 - Tiaret" },
  { value: "15", label: "15 - Tizi Ouzou" },
  { value: "16", label: "16 - Alger" },
  { value: "17", label: "17 - Djelfa" },
  { value: "18", label: "18 - Jijel" },
  { value: "19", label: "19 - Sétif" },
  { value: "20", label: "20 - Saïda" },
  { value: "21", label: "21 - Skikda" },
  { value: "22", label: "22 - Sidi Bel Abbès" },
  { value: "23", label: "23 - Annaba" },
  { value: "24", label: "24 - Guelma" },
  { value: "25", label: "25 - Constantine" },
  { value: "26", label: "26 - Médéa" },
  { value: "27", label: "27 - Mostaganem" },
  { value: "28", label: "28 - M'Sila" },
  { value: "29", label: "29 - Mascara" },
  { value: "30", label: "30 - Ouargla" },
  { value: "31", label: "31 - Oran" },
  { value: "32", label: "32 - El Bayadh" },
  { value: "33", label: "33 - Illizi" },
  { value: "34", label: "34 - Bordj Bou Arréridj" },
  { value: "35", label: "35 - Boumerdès" },
  { value: "36", label: "36 - El Tarf" },
  { value: "37", label: "37 - Tindouf" },
  { value: "38", label: "38 - Tissemsilt" },
  { value: "39", label: "39 - El Oued" },
  { value: "40", label: "40 - Khenchela" },
  { value: "41", label: "41 - Souk Ahras" },
  { value: "42", label: "42 - Tipaza" },
  { value: "43", label: "43 - Mila" },
  { value: "44", label: "44 - Aïn Defla" },
  { value: "45", label: "45 - Naâma" },
  { value: "46", label: "46 - Aïn Témouchent" },
  { value: "47", label: "47 - Ghardaïa" },
  { value: "48", label: "48 - Relizane" },
  { value: "49", label: "49 - El M'Ghair" },
  { value: "50", label: "50 - El Meniaa" },
  { value: "51", label: "51 - Ouled Djellal" },
  { value: "52", label: "52 - Bordj Baji Mokhtar" },
  { value: "53", label: "53 - Béni Abbès" },
  { value: "54", label: "54 - Timimoun" },
  { value: "55", label: "55 - Touggourt" },
  { value: "56", label: "56 - Djanet" },
  { value: "57", label: "57 - In Salah" },
  { value: "58", label: "58 - In Guezzam" },
];

export const TENDER_TYPE_OPTIONS = [
  { value: "national_call", label: "National call for tenders" },
  { value: "international_call", label: "National and International Call for Tenders" },
  { value: "sale_notice", label: "Sale notice" },
  { value: "international_consultation", label: "International consultation" },
  { value: "national_consultation", label: "National consultation" },
  { value: "expressions_interest", label: "Expressions of Interest" },
  { value: "national_preselection", label: "National Preselection" },
  { value: "adjudication", label: "Adjudication" },
];
