// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://achevndenwxikpbabzop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjaGV2bmRlbnd4aWtwYmFiem9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyOTcwMTcsImV4cCI6MjA0OTg3MzAxN30.d4j9VK5XCCTefB8QdRdT6Wy9I17YAxQ5kK8kBXtBK54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
